### ISSUE TITLE
Runtime error in SAPI

### ISSUE THREAD

**Issue by priyacdac** [m-toman/SALB#2]
In windows, using text to speech application try to load your sapi voice LEO and SLT. But we are getting following error
Runtime error -> rundll32.exe
I downloaded your code and compiled it in visual studio 2012 in release mode in windows 8 64 bit.

**Comment by m-toman** [comment]
Hi,
I've researched that issue a bit and it seems those rundll32 errors seem to be a rather tricky error with a lot of possible causes. Do you have more information?

We found with other (non-SALB) applications that often a Windows Update solved SAPI issues.

I usually use DSpeech for testing SAPI voices: http://dimio.altervista.org/eng/ but I think it's only 32-bit, so only loading 32-bit SAPI voices.

**Comment by priyacdac** [comment]
Hi,
Thanks for your response. We are building this project using Visual studio
12.0 with Windows SDK 8.0 at Windows 8 machine. During the building of
project sapiPS we getting below syntax error:
1>------ Build started: Project: sapiPS, Configuration: Release x64 ------
1> dlldata.c
1> htssapi_i.c
1> htssapi_p.c
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2309): error
C2059: syntax error : ':'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2790): error
C2143: syntax error : missing ')' before '

*' 1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2790):
error C2081: 'SPRECORESULTINFOEX' : name in formal parameter list illegal
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2790): error
C2143: syntax error : missing ';' before '*'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2790): error
C2059: syntax error : '*'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2790): error
C2059: syntax error : ')'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2793): error
C2059: syntax error : '}'
1> Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

It seems, we are using wrong version of windows SDK. Kindly let us know
what are the versions of Visual Studio and Windows SDK, windows version you
used for building this project.

**Comment by priyacdac** [comment]
Hi,
Thanks for your response. We are building this project using Visual studio
12.0 with Windows SDK 8.0 at Windows 8 machine. During the building of
project sapiPS we getting below syntax error:
1>------ Build started: Project: sapiPS, Configuration: Release x64 ------
1> dlldata.c
1> htssapi_i.c
1> htssapi_p.c
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2309): error
C2059: syntax error : ':'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2790): error
C2143: syntax error : missing ')' before '

*' 1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2790):
error C2081: 'SPRECORESULTINFOEX' : name in formal parameter list illegal
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2790): error
C2143: syntax error : missing ';' before '*'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2790): error
C2059: syntax error : '*'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2790): error
C2059: syntax error : ')'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\sapiddk.h(2793): error
C2059: syntax error : '}'
1> Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

It seems, we are using wrong version of windows SDK. Kindly let us know
what are the versions of Visual Studio and Windows SDK, windows version you
used for building this project.

**Comment by m-toman** [comment]
Hi,

personally I don't use VS 2012 anymore, but that was what I used back then. I decided to not upgrade the project here so people are not forced to use Visual Studio 2015.

The sapiPS project is generated by Visual Studio and as far as I know not supposed to be built directly (but automatically generates code).

I just opened the the solution file with VS 2015, Community Edition and built the "sapi" project - release, win32. Seems I'm using the Windows SDK 8.1, see also the log below:
```
4>------ Build started: Project: sapi, Configuration: Release Win32 ------
4>  Processing .\htssapi.idl
4>  htssapi.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.idl
4>  oaidl.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\objidl.idl
4>  objidl.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\unknwn.idl
4>  unknwn.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\shared\wtypes.idl
4>  wtypes.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\shared\wtypesbase.idl
4>  wtypesbase.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\shared\basetsd.h
4>  basetsd.h
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\shared\guiddef.h
4>  guiddef.h
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\ocidl.idl
4>  ocidl.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\oleidl.idl
4>  oleidl.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\servprov.idl
4>  servprov.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\urlmon.idl
4>  urlmon.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\msxml.idl
4>  msxml.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\sapiddk.idl
4>  sapiddk.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\sapi.idl
4>  sapi.idl
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.acf
4>  oaidl.acf
4>  Processing C:\Program Files (x86)\Windows Kits\8.1\Include\um\ocidl.acf
4>  ocidl.acf
4>  stdafx.cpp
4>  dllmain.cpp
4>  htssapi.cpp
4>  htstts.cpp
4>htstts.cpp(302): warning C4101: 'e': unreferenced local variable
4>htstts.cpp(307): warning C4101: 'e': unreferenced local variable
4>htstts.cpp(312): warning C4101: 'e': unreferenced local variable
4>  Generating Code...
4>  htssapi_i.c
4>  manager.lib(Text.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
4>     Creating library .\bin\htstts.lib and object .\bin\htstts.exp
4>  Generating code
4>  Finished generating code
4>  htssapi.vcxproj -> C:\met\work\SALB\sapi\.\bin\htstts.dll
```

**Comment by priyacdac** [comment]
Hi sir,

We are trying to integrate Indian language hindi voice with SALB SAPI
framework. We compiled the entire framework in visual studio 2017 and it is
successfully compiled and .exe file generated using install script in your
framework.

When we try to call SAPI with any screen readers like NVDA, windows
narrator, after sometime voice is crashing.

Do you tested your voice, leo with any of these screen reader? We tried
with your leo voice with these screen readers, it showing same error i.e.
crashing after sometime.

Can you please me to solve this issue i.e. to run hts voice with screen
reader.

Thanks,
Priya Hemane
Project Engineer,
CDAC, Mumbai

**Comment by m-toman** [comment]
Hi,

great that you got it to work.
We tested the Leo voice with Narrator on Windows 7 a while back but our 
main focus was JAWS.
We did not experience the crashes you mentioned but I could imagine that 
there are problems with the encoding?

I have some code here: 
https://github.com/m-toman/SALB/blob/master/engine/manager/src/utils.cpp
that deals with German special characters, perhaps that's an issue?

Debugging SAPI is pretty painful, I would suggest modifying the CLI and 
e.g. synthesize sentences in a loop and see if you can reproduce the 
crash there.

Best,
Markus


Am 2017-07-03 13:17, schrieb priyacdac:
