### ISSUE TITLE
TTSEngine.java

### ISSUE THREAD

**Issue by Shallowmallow** [m-toman/SALB#4]
Hi !
Would love to port this on android but TTSEngine.java doesn't want to compile . Where does currentElement come from ?

```
		AudioTrack audioTrack = new AudioTrack(
				AudioManager.STREAM_MUSIC,
				MODEL_FREQUENCY,
				AudioFormat.CHANNEL_OUT_MONO,
				AudioFormat.ENCODING_PCM_16BIT,
				currentElement.getSampleCache().length * 2,
				AudioTrack.MODE_STATIC);

		audioTrack.write(currentElement.getSampleCache(), 0,
				currentElement.getSampleCache().length);```

**Comment by m-toman** [comment]
Hi,
I'm sorry, the Java version was extracted from a larger, proprietary codebase that I'm not allowed to share.
I suspect if you just replace "currentElement.getSampleCache()" with "cache" it should work.
If you could verify this, I'll change it here (or accept a pull request if you prefer that).

Thanks

**Comment by Shallowmallow** [comment]
Thanks, it compiles now with your solution. :)
Now, I have a problem with the sound playing far too fast. If ever i find a solution, I'll  post it here.

**Comment by m-toman** [comment]
Great, is the sampling rate correct?

**Comment by Shallowmallow** [comment]
I just changed in SALB.cpp
(*properties)[PROPERTY_KEY_RATE]        = szRate;

to
(*properties)[PROPERTY_KEY_RATE]        = 1;

and it worked :)

**Comment by m-toman** [comment]
Thanks for the info, I changed it here: https://github.com/m-toman/SALB/blob/master/android/at/ftw/speechsynthesis/TTSEngine.java#L42
The sampling rate was used here instead of the speaking rate... wonder how this even compiled.
